### ISSUE TITLE
build error -  : method getChunk()

### ISSUE THREAD

**Issue by mstram** [eisental/BasicCircuits#12]
Getting error from mvn clean package install :

D:\Maven\BasicCircuits>mvn -e clean package install
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.tal:BasicCircuits:jar:beta
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 20, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building BasicCircuits beta
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ BasicCircuits ---
[INFO] Deleting D:\Maven\BasicCircuits\target
[INFO] 
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ BasicCircuits ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ BasicCircuits ---
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 44 source files to D:\Maven\BasicCircuits\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\pixel.java:[102,32] cannot find symbol
symbol  : method getChunk()
location: class org.bukkit.Location
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.078s
[INFO] Finished at: Sun Jan 01 05:06:38 EST 2012
[INFO] Final Memory: 6M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project BasicCircuits: Compilation failure
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\pixel.java:[102,32] cannot find symbol
[ERROR] symbol  : method getChunk()
[ERROR] location: class org.bukkit.Location
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project BasicCircuits: Compilation failure
\Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\pixel.java:[102,32] cannot find symbol
symbol  : method getChunk()
location: class org.bukkit.Location

```
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
```

Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
\Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\pixel.java:[102,32] cannot find symbol
symbol  : method getChunk()
location: class org.bukkit.Location

```
at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:656)
at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:128)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
... 19 more
```

[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
# [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

I did build the current RedChips before trying to build BasicCircuits   and though it says "some problems ..." it did build the RedstoneChips-beta.jar :

D:\Maven\RedStoneChips>mvn clean package install
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.tal:RedstoneChips:jar:beta
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 26, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building RedstoneChips beta
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ RedstoneChips ---
[INFO] Deleting D:\Maven\RedStoneChips\target
[INFO]
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ RedstoneChips ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ RedstoneChips ---
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 65 source files to D:\Maven\RedStoneChips\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.4.3:testResources (default-testResources) @ RedstoneChips ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\Maven\RedStoneChips\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ RedstoneChips ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.7.2:test (default-test) @ RedstoneChips ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.3.1:jar (default-jar) @ RedstoneChips ---
[INFO] Building jar: D:\Maven\RedStoneChips\target\RedstoneChips-beta.jar
[INFO]
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ RedstoneChips ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ RedstoneChips ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.4.3:testResources (default-testResources) @ RedstoneChips ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\Maven\RedStoneChips\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ RedstoneChips ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.7.2:test (default-test) @ RedstoneChips ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.3.1:jar (default-jar) @ RedstoneChips ---
[INFO]
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ RedstoneChips ---
[INFO] Installing D:\Maven\RedStoneChips\target\RedstoneChips-beta.jar to C:\Documents and Settings\Mike.m2\repository\org\tal\RedstoneChips\beta\RedstoneChips-beta.jar
[INFO] Installing D:\Maven\RedStoneChips\pom.xml to C:\Documents and Settings\Mike.m2\repository\org\tal\RedstoneChips\beta\RedstoneChips-beta.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.922s
[INFO] Finished at: Sun Jan 01 04:24:30 EST 2012
[INFO] Final Memory: 7M/27M
[INFO] ------------------------------------------------------------------------

**Comment by eisental** [comment]
I made some changes to pom.xml which should solve this. I think it was compiling against an old bukkit version.
In any case, don't forget to compile RC before BC

**Comment by mstram** [comment]
I'll try it, but I noticed it was failing in pixel.java, where it
looks like you changed the way the you are testing for loaded chunks.

**Comment by mstram** [comment]
## Still not working

D:\Maven\BasicCircuits>rem mvn -e -X clean package install 

D:\Maven\BasicCircuits>mvn -e clean package install 
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building BasicCircuits beta
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ BasicCircuits ---
[INFO] Deleting D:\Maven\BasicCircuits\target
[INFO] 
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ BasicCircuits ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ BasicCircuits ---
[INFO] Compiling 44 source files to D:\Maven\BasicCircuits\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\pixel.java:[104,32] cannot find symbol
symbol  : method getChunk()
location: class org.bukkit.Location
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.063s
[INFO] Finished at: Sun Jan 01 09:10:43 EST 2012
[INFO] Final Memory: 6M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project BasicCircuits: Compilation failure
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\pixel.java:[104,32] cannot find symbol
[ERROR] symbol  : method getChunk()
[ERROR] location: class org.bukkit.Location
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project BasicCircuits: Compilation failure
\Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\pixel.java:[104,32] cannot find symbol
symbol  : method getChunk()
location: class org.bukkit.Location

```
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
```

Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
\Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\pixel.java:[104,32] cannot find symbol
symbol  : method getChunk()
location: class org.bukkit.Location

```
at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:656)
at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:128)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
... 19 more
```

[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by eisental** [comment]
I think the problem with getChunk() is that it was added to a recent bukkit version. Did you build RedstoneChips with the new pom.xml before trying to rebuild BasicCircuits?

**Comment by mstram** [comment]
Can you send me the BasicCircuits.jar ?

On 1/1/12, Tal Eisenberg
reply@reply.github.com
wrote:

**Comment by mstram** [comment]
Or have you updated the main download link ?
